apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: miztiik-secured
spec:
  privileged: false   # DO NOT ALLOW privileged pods!
  # hostNetwork: false  # DO NOT ALLOW   
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
